// <auto-generated />
using Gerenciamento_Conferencias.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerenciamento_Conferencias.Migrations
{
    [DbContext(typeof(GerenciamentoConferenciasContext))]
    partial class GerenciamentoConferenciasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Conferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TbConferencia", (string)null);
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.NetworkingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Inicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrilhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId")
                        .IsUnique();

                    b.ToTable("TbNetworkingEvent", (string)null);
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Palestra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Inicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrilhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.ToTable("TbPalestra", (string)null);
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Trilha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.ToTable("TbTrilha", (string)null);
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.NetworkingEvent", b =>
                {
                    b.HasOne("Gerenciamento_Conferencias.Data.Table.Trilha", "Trilha")
                        .WithOne("NetworkingEvent")
                        .HasForeignKey("Gerenciamento_Conferencias.Data.Table.NetworkingEvent", "TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Palestra", b =>
                {
                    b.HasOne("Gerenciamento_Conferencias.Data.Table.Trilha", "Trilha")
                        .WithMany("Palestras")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Trilha", b =>
                {
                    b.HasOne("Gerenciamento_Conferencias.Data.Table.Conferencia", "Conferencia")
                        .WithMany("Trilhas")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Conferencia", b =>
                {
                    b.Navigation("Trilhas");
                });

            modelBuilder.Entity("Gerenciamento_Conferencias.Data.Table.Trilha", b =>
                {
                    b.Navigation("NetworkingEvent");

                    b.Navigation("Palestras");
                });
#pragma warning restore 612, 618
        }
    }
}
